name: "Run mypy"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install mypy
      run: |
        python -m pip install --upgrade pip
        pip install mypy
    - name: Run mypy
      run: |
        mypy src/ --ignore-missing-imports
